version: "3.1"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "8000:80" # Expose WordPress on port 8000 of the host
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./html:/var/www/html # Mount the WordPress files
      - ./plugins:/var/www/html/wp-content/plugins # Optional: Mount a plugins directory
      - ./themes:/var/www/html/wp-content/themes # Optional: Mount a themes directory
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: {}
